CREATE DATABASE Biblioteca;

USE Biblioteca;

CREATE TABLE Pais(
Id_Pais INT AUTO_INCREMENT PRIMARY KEY,
Nombre VARCHAR(50) NOT NULL
);

CREATE TABLE Departamento(
Id_Departamento INT AUTO_INCREMENT PRIMARY KEY,
Nombre VARCHAR(50) NOT NULL,
Id_Pais INT NOT NULL,
FOREIGN KEY (Id_Pais) REFERENCES Pais(Id_Pais)
ON DELETE CASCADE
ON UPDATE CASCADE
);

CREATE TABLE Municipio(
Id_Municipio INT AUTO_INCREMENT PRIMARY KEY,
Nombre VARCHAR(50) NOT NULL,
Id_Departamento INT NOT NULL,
FOREIGN KEY (Id_Departamento) REFERENCES Departamento(Id_Departamento)
ON DELETE CASCADE
ON UPDATE CASCADE
);

CREATE TABLE Autor(
Id_Autor INT AUTO_INCREMENT PRIMARY KEY,
Primer_Nombre VARCHAR(50) NOT NULL,
Segundo_Nombre VARCHAR(50),
Primer_Apellido VARCHAR(50) NOT NULL,
Segundo_Apellido VARCHAR(50),
Id_Pais INT NOT NULL,
FOREIGN KEY (Id_Pais) REFERENCES Pais(Id_Pais)
ON DELETE CASCADE
ON UPDATE CASCADE
);

CREATE TABLE Editorial(
Id_Editorial INT AUTO_INCREMENT PRIMARY KEY,
Nombre VARCHAR(50) NOT NULL,
Id_Pais INT NOT NULL,
FOREIGN KEY (Id_Pais) REFERENCES Pais(Id_Pais)
ON DELETE CASCADE
ON UPDATE CASCADE
);

CREATE TABLE Libro(
Id_Libro INT AUTO_INCREMENT PRIMARY KEY,
Titulo VARCHAR(200) NOT NULL,
Fecha_Publicacion DATE NOT NULL,
ISBN VARCHAR(20) NOT NULL,
Id_Editorial INT NOT NULL,
FOREIGN KEY (Id_Editorial) REFERENCES Editorial(Id_Editorial)
ON DELETE CASCADE
ON UPDATE CASCADE
);

CREATE TABLE Categoria(
Id_Categoria INT AUTO_INCREMENT PRIMARY KEY,
Nombre VARCHAR(50) NOT NULL
);

CREATE TABLE Miembro(
Id_Miembro INT AUTO_INCREMENT PRIMARY KEY,
Primer_Nombre VARCHAR(50) NOT NULL,
Segundo_Nombre VARCHAR(50),
Primer_Apellido VARCHAR(50) NOT NULL,
Segundo_Apellido VARCHAR(50),
Telefono VARCHAR(20) NOT NULL,
Fecha_Registro DATE NOT NULL,
Id_Municipio INT NOT NULL,
FOREIGN KEY (Id_Municipio) REFERENCES Municipio(Id_Municipio)
ON DELETE CASCADE
ON UPDATE CASCADE
);

CREATE TABLE Empleado(
Id_Empleado INT AUTO_INCREMENT PRIMARY KEY,
Primer_Nombre VARCHAR(50) NOT NULL,
Segundo_Nombre VARCHAR(50),
Primer_Apellido VARCHAR(50) NOT NULL,
Segundo_Apellido VARCHAR(50),
Puesto VARCHAR(50) NOT NULL,
Fecha_Contratacion DATE NOT NULL
);

CREATE TABLE Prestamo(
Id_Prestamo INT AUTO_INCREMENT PRIMARY KEY,
Id_Miembro INT NOT NULL,
Id_Empleado INT NOT NULL,
Fecha_Prestamo DATE NOT NULL,
Fecha_Devolucion DATE NOT NULL,
FOREIGN KEY (Id_Miembro) REFERENCES Miembro(Id_Miembro)
ON DELETE CASCADE
ON UPDATE CASCADE,
FOREIGN KEY (Id_Empleado) REFERENCES Empleado(Id_Empleado)
ON DELETE CASCADE
ON UPDATE CASCADE
);

CREATE TABLE Libro_Autor(
Id_Libro_Autor INT AUTO_INCREMENT PRIMARY KEY,
Id_Libro INT NOT NULL,
Id_Autor INT NOT NULL,
FOREIGN KEY (Id_Libro) REFERENCES Libro(Id_Libro),
FOREIGN KEY (Id_Autor) REFERENCES Autor(Id_Autor)
);

CREATE TABLE Libro_Categoria(
Id_Libro_Categoria INT AUTO_INCREMENT PRIMARY KEY,
Id_Libro INT NOT NULL,
Id_Categoria INT NOT NULL,
FOREIGN KEY (Id_Libro) REFERENCES Libro(Id_Libro)
ON DELETE CASCADE
ON UPDATE CASCADE,
FOREIGN KEY (Id_Categoria) REFERENCES Categoria(Id_Categoria)
ON DELETE CASCADE
ON UPDATE CASCADE
);

CREATE TABLE Detalle_Prestamo(
Id_Detalle_Prestamo INT AUTO_INCREMENT PRIMARY KEY,
Id_Prestamo INT NOT NULL,
Id_Libro INT NOT NULL,
FOREIGN KEY (Id_Prestamo) REFERENCES Prestamo(Id_Prestamo),
FOREIGN KEY (Id_Libro) REFERENCES Libro(Id_Libro)
);